### ISSUE TITLE
Constantly hitting error "Terminal size too small"

### ISSUE THREAD

**Issue by howardchen003** [r3w0p/caravan#3]
Hi! I was wondering if there was a way I'm suppose to launch the game or if I'm just doing it wrong. I constantly get the error of 'terminal size too small' even if I change both the font as well as the window size.

**Comment by r3w0p** [comment]
Hello! Hmm, that's strange, I'm not sure what the solution could be. To get it to work for me, I use the Windows PowerShell on full screen with a relatively small font. (I intend to eventually rewrite this program to use a TUI instead of the hacky ncurses approach I used.)

**Comment by r3w0p** [comment]
![1](https://github.com/r3w0p/caravan/assets/23155844/da2a62d9-ca54-4e3e-b7e8-a290d46a48fe)

I've tried running the caravan EXE file just now and I am able to get it to run, as you can see with the attached image.

**Comment by howardchen003** [comment]
I guess it only works in PowerShell and not Terminal. Strange. Just got it to work. Thanks!

**Comment by r3w0p** [comment]
I'm glad you got it working. I tested Caravan on both PowerShell and Terminal / Command Prompt, and it worked for both.
